########################################
# Environnement
########################################

# Dev environment
@baseUrl = http://localhost:8080
# Staging environment
#@baseUrl = https://products.localhost:5443

########################################
# Tests ProductResource V
########################################

### GET all products v1
GET {{baseUrl}}/api/v1/products
Accept: application/json

### GET product by SKU v1
GET {{baseUrl}}/api/v1/products/P001
Accept: application/json

### POST create product v1
POST {{baseUrl}}/api/v1/products
Content-Type: application/json

{
  "sku": "P005",
  "name": "Produit 5",
  "price": 50.0,
  "stock": 500
}

### DELETE product v1
DELETE {{baseUrl}}/api/v1/products/P005
